### ISSUE TITLE
Change default tld from '.localhost' to '.test'

### ISSUE THREAD

**Issue by r-bt** [jeansaad/chalet#13]
Hey,

First thanks for maintaining this fork, its great :) On hotel there's an issue about .localhost domains and Chrome https://github.com/typicode/hotel/issues/326. The gist is that Chrome bypasses the proxy for .localhost domains. 

Just wondering if you'd accept a PR to change the default tld to '.test' so chalet can work out of the box with Chrome

**Comment by jeansaad** [comment]
First off, apologies for the late reply!

I personally prefer .test domain and use that locally so would definitely be open to making this the default. One of the reasons that I like to use this TLD is because it is one of the few protected ones an quite frankly shorter than .localhost.

https://en.m.wikipedia.org/wiki/.test

Feel free to submit a PR for this!
